### ISSUE TITLE
JnaPtyExecutor seems broken on linux x86_64

### ISSUE THREAD

**Issue by volth** [traff/pty4j#44]
JnaPtyExecutor seems broken on linux x86_64

There are no visible errors, just no output is produced

testcase:
```scala
    val cmd = "bash"::"-c"::"ls -l"::Nil
    val p = com.pty4j.PtyProcess.exec(cmd.toArray, System.getenv, null, true)
    val threads = List(new Thread { override def run() { IOUtils.copy(p.getInputStream, System.out) }; start() },
                       new Thread { override def run() { IOUtils.copy(p.getErrorStream, System.out) }; start() })
    val exitCode = p.waitFor()
    threads foreach (_.join)
```

it works with the native library

**Comment by volth** [comment]
Another testcase is [jediterm](https://github.com/JetBrains/jediterm) with deleted ```libpty.so``` forcing ```pty4j``` to fall back to JNA.
And it does not work

**Comment by segrey** [comment]
JnaPtyExecutor was deleted in https://github.com/traff/pty4j/commit/0b1b6cdcc5f22b6837c3d2eb0d7adea6e974536e
